#!/bin/bash

test -e /etc/default/airmake && . /etc/default/airmake
test -e airmakerc && . airmakerc

case "$1" in
"initstore")
	echo "Initializing keystore..."
	java -jar "${SDKDIR}/lib/adt.jar" -certificate -cn SelfSign -ou Dev -o "example" -c US 2048-RSA "${AIRKEYSTORE}" "${AIRSTOREPASS}"
	;;
"run")
	echo "Running package ${AIRMANIFEST}..."
	"${SDKDIR}/bin/adl" "${AIRMANIFEST}"
	;;
"package")
	echo "Building package ${AIRFILE}..."
	java -jar "${SDKDIR}/lib/adt.jar" -package -storetype pkcs12 -keystore "${AIRKEYSTORE}" -storepass "${AIRSTOREPASS}" "${AIRFILE}" "${AIRMANIFEST}" -C "${AIRDIR}" "${AIRFILES}"
	ls -al "${AIRFILE}"
	;;
"update")
	echo "Updating classes..."
	../bin/lepton airmake update air/src/airbinder.js
	;;
"scaffold")
	echo 'Creating application...'
	test -d air || mkdir air
	test -d air/src || mkdir air/src
	test -d air/build || mkdir air/build
	test -d air/icons || mkdir air/icons
	cp -v 'res/air/application.xml' 'air/application.xml'
	cp -v 'res/air/airmakerc' 'airmakerc'
	cp -v 'res/air/binder.php' 'air/binder.php'
	cp -v 'res/air/src/index.html' 'air/src/index.html'
	cp -v 'res/air/prototype.js' 'air/src/prototype.js'
	cp -vr 'res/air/icons/lepton-16.png' 'air/icons/lepton-16.png'
	cp -vr 'res/air/icons/lepton-32.png' 'air/icons/lepton-32.png'
	cp -vr 'res/air/icons/lepton-48.png' 'air/icons/lepton-48.png'
	cp -vr 'res/air/icons/lepton-128.png' 'air/icons/lepton-128.png'
	;;
"create")
	$0 initstore
	$0 scaffold
	$0 update
	;;
*)
	echo "Use: `basename $0` {initstore|package|run|scaffold|update|create}"
	echo '  initstore  - create new crypto store'
	echo '  package  - create .air package'
	echo '  run  - run package -- for testing'
	echo '  scaffold  - create the initial structure for an airbound app'
	echo '  update  - update the airbinder bindings'
	echo '  create  - initialize EVERYTHING.'
	;;
esac
